In [1]:
import numpy as np

*QUESTION 1*

In [2]:
npArray=np.array(range (2,51,3))
print(npArray)
print(type(npArray))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]
<class 'numpy.ndarray'>


*QUESTION 2*

In [3]:
lst1=list(input().split(','))
lst1=[int(i) for i in lst1]
lst2=list(input().split(','))
lst2=[int(i) for i in lst2]
ar1=np.array(lst1)
ar2=np.array(lst2)
print(np.concatenate((ar1,ar2)))
print(np.sort(np.concatenate((ar1,ar2))))


1,5,23,42,19
5,79,99,68,39
[ 1  5 23 42 19  5 79 99 68 39]
[ 1  5  5 19 23 39 42 68 79 99]


*QUESTION 3*

In [4]:
a=np.random.rand(3,5)
#print(a)
print(a.shape)
print(a.size)

(3, 5)
15


*QUESTION 4*

In [5]:
ar=np.array([2,1,3])
print(ar.shape)
ar1=ar[np.newaxis].shape
ar2=np.expand_dims(ar,axis=1).shape
print(ar1)
print(ar2)

(3,)
(1, 3)
(3, 1)


*QUESTION 5*

In [6]:
ar1=np.random.rand(3,3)
ar2=np.random.rand(3,3)
print(np.vstack((ar1,ar2)),"\n")
print(np.hstack((ar1,ar2)))

[[0.40736242 0.47187397 0.53871857]
 [0.56110529 0.86786569 0.62573697]
 [0.87777981 0.14507464 0.14526383]
 [0.20655178 0.50088629 0.28062325]
 [0.24464942 0.87941689 0.84868259]
 [0.65714831 0.02796338 0.16593869]] 

[[0.40736242 0.47187397 0.53871857 0.20655178 0.50088629 0.28062325]
 [0.56110529 0.86786569 0.62573697 0.24464942 0.87941689 0.84868259]
 [0.87777981 0.14507464 0.14526383 0.65714831 0.02796338 0.16593869]]


*QUESTION 6*

In [7]:
ar=np.array([1,2,2,5,4,6,8,9,12,1,1,2,5,6,8,9,8,8,5,2,5,12,45,4,5,121,2,1,6,44,4,64,6,6,6,1,31,61])
unique,occur=np.unique(ar,return_counts=True)

for i,j in zip(unique,occur):
  print(i ,"=>",j)

1 => 5
2 => 5
4 => 3
5 => 5
6 => 6
8 => 4
9 => 2
12 => 2
31 => 1
44 => 1
45 => 1
61 => 1
64 => 1
121 => 1
